export const theme = {
  colors: {
    obsidian: '#0A0A0F',
    volt: '#E8FF00',
    signalGreen: '#4ADE80',
    offWhite: '#F5F5F0',
    background: '#FFFFFF',
    backgroundDark: '#0A0A0F',
    surface: '#F5F5F5',
    surfaceDark: '#161620',
    surfaceElevated: '#F5F5F0',
    card: '#FFFFFF',
    cardDark: '#1A1D27',
    text: '#0A0A0F',
    textLight: '#FFFFFF',
    textMuted: '#9E9E9E',
    textFaint: '#BBBBBB',
    textOnDark: 'rgba(255,255,255,0.7)',
    textOnDarkMuted: 'rgba(255,255,255,0.4)',
    primary: '#000000',
    accent: '#00C853',
    success: '#00C853',
    danger: '#FF3B30',
    warning: '#F59E0B',
    border: '#E0E0E0',
    borderDark: 'rgba(255,255,255,0.08)',
    borderAccent: 'rgba(232,255,0,0.25)',
    overlayMedium: 'rgba(10,10,15,0.45)',
    overlayDark: 'rgba(10,10,15,0.72)',
    black: '#000000',
    /** Semantic aliases used by restored screens */
    textPrimary: '#000000',
    textSecondary: '#757575',
    textWhite: '#FFFFFF',
    successLight: '#E8F5E9',
    primaryLight: '#F5F5F5',
    warningLight: '#FFFBEB',
  },
  typography: {
    xs: 11,
    sm: 12,
    base: 14,
    md: 15,
    lg: 17,
    xl: 20,
    xxl: 24,
    hero: 32,
    regular: '400',
    medium: '500',
    semibold: '600',
    bold: '700',
    tight: -0.5,
    normal: 0,
    wide: 0.5,
    wider: 1,
    widest: 1.5,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    xxxl: 32,
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    full: 999,
  },
  components: {
    screenLight: {
      flex: 1,
      backgroundColor: '#FAFAFA',
    },
    screenDark: {
      flex: 1,
      backgroundColor: '#0A0A0F',
    },
    card: {
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      padding: 16,
      borderWidth: 1,
      borderColor: '#E8E8E8',
    },
    cardDark: {
      backgroundColor: '#161620',
      borderRadius: 16,
      padding: 16,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
    },
    ctaButton: {
      height: 52,
      backgroundColor: '#0A0A0F',
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
    },
    ctaButtonText: {
      color: '#FFFFFF',
      fontSize: 15,
      fontWeight: '600',
      letterSpacing: 0.2,
    },
    accentButton: {
      height: 52,
      backgroundColor: '#E8FF00',
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
    },
    accentButtonText: {
      color: '#0A0A0F',
      fontSize: 15,
      fontWeight: '700',
      letterSpacing: 0.2,
    },
    input: {
      backgroundColor: '#FFFFFF',
      borderWidth: 1,
      borderColor: '#E8E8E8',
      borderRadius: 12,
      minHeight: 48,
      paddingHorizontal: 16,
      fontSize: 14,
      color: '#0A0A0F',
    },
    inputDark: {
      backgroundColor: 'rgba(255,255,255,0.06)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.1)',
      borderRadius: 12,
      minHeight: 48,
      paddingHorizontal: 16,
      fontSize: 14,
      color: '#FFFFFF',
    },
  },
};

export const colors = theme.colors;
export const typography = theme.typography;
export const spacing = theme.spacing;
export const radius = theme.radius;
export const shadows = {
  card: {
    shadowColor: theme.colors.black,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 20,
    elevation: 6,
  },
  modal: {
    shadowColor: theme.colors.black,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.14,
    shadowRadius: 28,
    elevation: 12,
  },
};
